name: Frontend E2E Tests

on: [push]

jobs:
  e2e-test:
    name: Run Frontend E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run E2E tests
        working-directory: ./frontend
        run: npm run test-e2e -- --ci
