name: Lugia Frontend E2E Tests

on:
  push:
    paths-ignore:
      - 'infrastructure/**'

jobs:
  e2e-test:
    name: Run lugia-frontend E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run E2E tests
        working-directory: ./lugia-frontend
        run: npm run test-e2e -- --ci
